### ISSUE TITLE
UX feedback: consolidated Receive/Mint and Send/Melt

### ISSUE THREAD

**Issue by tanx** [zeugmaster/macadamia#5]
Hey, thanks for your work. This app is super clean. Been thinking recently ecash needs a WalletOfSatoshi type of app that’s really simple to get started. My main feedback is to just have send/receive buttons on the homescreen and default to Lightning payments. The ecash bearer instruments are neat but probably too complicated to expose in the homescreen UI.

**Comment by zeugmaster** [comment]
Hey @tanx ! thanks for the feedback! That is one of the next things I am working on, but I have a very specific UX in mind that's going to be a little more tricky to implement. The goal is to reduce clutter and also steps/taps. Removing one just to add another is something i'd like to avoid. If you have a lot of experience with UIKit and/or SwiftUI let me know!

**Comment by zeugmaster** [comment]
The UI has been simplified, text tokens will be part of the UX for the foreseeable future but gradually replaced with more user friendly representations of ecash. Thanks @tanx for the feedback!
